/*
SuprSend API

SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.

The version of the OpenAPI document: 1.2.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * urls of social media accounts of the brand. If you really want to remove any social link, you must set its value=\"\" (instead of null)
 * @export
 * @interface BrandCreateOrUpdateRequestSocialLinks
 */
export interface BrandCreateOrUpdateRequestSocialLinks {
    /**
     * link of brand website. While updating a social link, if you want to remove the link, you must the value=\"\" (instead of null)
     * @type {string}
     * @memberof BrandCreateOrUpdateRequestSocialLinks
     */
    'website'?: string;
    /**
     * brand facebook page link
     * @type {string}
     * @memberof BrandCreateOrUpdateRequestSocialLinks
     */
    'facebook'?: string;
    /**
     * brand linkedin page link
     * @type {string}
     * @memberof BrandCreateOrUpdateRequestSocialLinks
     */
    'linkedin'?: string;
    /**
     * brand twitter page link
     * @type {string}
     * @memberof BrandCreateOrUpdateRequestSocialLinks
     */
    'twitter'?: string;
    /**
     * brand instagram page link
     * @type {string}
     * @memberof BrandCreateOrUpdateRequestSocialLinks
     */
    'instagram'?: string;
    /**
     * brand medium page link
     * @type {string}
     * @memberof BrandCreateOrUpdateRequestSocialLinks
     */
    'medium'?: string;
    /**
     * brand discord page link
     * @type {string}
     * @memberof BrandCreateOrUpdateRequestSocialLinks
     */
    'discord'?: string;
    /**
     * brand telegram page link
     * @type {string}
     * @memberof BrandCreateOrUpdateRequestSocialLinks
     */
    'telegram'?: string;
    /**
     * brand youtube page link
     * @type {string}
     * @memberof BrandCreateOrUpdateRequestSocialLinks
     */
    'youtube'?: string;
}

