/*
SuprSend API

SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.

The version of the OpenAPI document: 1.2.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BrandUpdateDefaultPreferenceRequest
 */
export interface BrandUpdateDefaultPreferenceRequest {
    /**
     * set `**opt_in**` to send notifications on all channels by default <br>  set `**opt_out**` to not send notifications in this category by default. For instance, **newsletter** <br>  set `**cant_unsubscribe**`if you do not want users to completely opt-out from this category. Notifications will always be sent on mandatory channels in this category.
     * @type {string}
     * @memberof BrandUpdateDefaultPreferenceRequest
     */
    'preference'?: string;
    /**
     * set it `false` to hide a category from user\'s preference page
     * @type {boolean}
     * @memberof BrandUpdateDefaultPreferenceRequest
     */
    'visible_to_subscriber'?: boolean;
    /**
     * Add mandatory channels that the user can\'t unsubscribe from if preference is `cant_unsubscribe`. Add channels as `email`, `sms`, `whatsapp`, `androidpush`, `inbox`, `iospush`, `slack`, `webpush`
     * @type {Array<string>}
     * @memberof BrandUpdateDefaultPreferenceRequest
     */
    'mandatory_channels'?: Array<string>;
}

