/*
SuprSend API

SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.

The version of the OpenAPI document: 1.2.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EventTriggerEventRequestUserOperationsInner
 */
export interface EventTriggerEventRequestUserOperationsInner {
    /**
     * Use this to add communication channels in user profile. Following channel keys: `$email`, `$sms`, `$whatsapp`, `$androidpush`, `$iospush`, `$slack`, `$webpush`, `$ms_teams`. Add channel as {\"$email\":\"user@example.com\"}
     * @type {object}
     * @memberof EventTriggerEventRequestUserOperationsInner
     */
    '$append'?: object;
    /**
     * Use this to remove communication channels from user profile. Following channel keys: `$email`, `$sms`, `$whatsapp`, `$androidpush`, `$iospush`, `$slack`, `$webpush`, `$ms_teams`. Define channel as {\"$email\":\"user@example.com\"}
     * @type {object}
     * @memberof EventTriggerEventRequestUserOperationsInner
     */
    '$remove'?: object;
    /**
     * Use this to set user properties like location, preferred language etc. You can define properties in key-value pair as `{\"$preferred_language\":\"hi\"}`
     * @type {object}
     * @memberof EventTriggerEventRequestUserOperationsInner
     */
    '$set'?: object;
    /**
     * Use this to remove properties from user profile. Define the property keys to be removed as \"$preferred_language\"
     * @type {Array<string>}
     * @memberof EventTriggerEventRequestUserOperationsInner
     */
    '$unset'?: Array<string>;
}

