/*
SuprSend API

SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.

The version of the OpenAPI document: 1.2.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EventTriggerEventRequestUserOperationsInner } from './event-trigger-event-request-user-operations-inner';

/**
 * 
 * @export
 * @interface EventTriggerEventRequest
 */
export interface EventTriggerEventRequest {
    /**
     * distinct_id of recipient who should receive the notification
     * @type {string}
     * @memberof EventTriggerEventRequest
     */
    'distinct_id': string;
    /**
     * Creating & updating users on SuprSend is done by sending an `$user_operations` event. All changes can be combined in one API call in an easy to replay format
     * @type {Array<EventTriggerEventRequestUserOperationsInner>}
     * @memberof EventTriggerEventRequest
     */
    '$user_operations'?: Array<EventTriggerEventRequestUserOperationsInner>;
    /**
     * string identifier for the event like `product_purchased`
     * @type {string}
     * @memberof EventTriggerEventRequest
     */
    'event': string;
    /**
     * a dictionary representing event attributes like `first_name`. Event properties can be used to pass template variables in case of event based trigger
     * @type {string}
     * @memberof EventTriggerEventRequest
     */
    'properties'?: string;
    /**
     * string identifier of the brand this event is associated with
     * @type {string}
     * @memberof EventTriggerEventRequest
     */
    'brand_id'?: string;
    /**
     * Idempotency key (valid for 24hours)
     * @type {string}
     * @memberof EventTriggerEventRequest
     */
    '$idempotency_key'?: string;
}

