/*
SuprSend API

SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.

The version of the OpenAPI document: 1.2.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PreferenceUpdateChannelPreferencesRequestChannelPreferencesInner } from './preference-update-channel-preferences-request-channel-preferences-inner';

/**
 * 
 * @export
 * @interface PreferenceUpdateChannelPreferencesRequest
 */
export interface PreferenceUpdateChannelPreferencesRequest {
    /**
     * Use this to update channel level user preferences. Set `is_restricted - true` if the channel is opted_out by the user. This will only send critical notifications to the user which can\'t be opted out
     * @type {Array<PreferenceUpdateChannelPreferencesRequestChannelPreferencesInner>}
     * @memberof PreferenceUpdateChannelPreferencesRequest
     */
    'channel_preferences'?: Array<PreferenceUpdateChannelPreferencesRequestChannelPreferencesInner>;
}

