/*
SuprSend API

SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.

The version of the OpenAPI document: 1.2.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SubscriberListCreateListRequest
 */
export interface SubscriberListCreateListRequest {
    /**
     * Unique string idenitifier of the list. Add an id which defines the type of users who are part of the list
     * @type {string}
     * @memberof SubscriberListCreateListRequest
     */
    'list_id': string;
    /**
     * Name of the List. Add a name which defines the type of users in the list
     * @type {string}
     * @memberof SubscriberListCreateListRequest
     */
    'list_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriberListCreateListRequest
     */
    'list_description'?: string;
}

