/*
SuprSend API

SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.

The version of the OpenAPI document: 1.2.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerContent
 */
export interface TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerContent {
    /**
     * 
     * @type {string}
     * @memberof TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerContent
     */
    'text'?: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerContent
     */
    'header'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerContent
     */
    'example'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerContent
     */
    'vendor_slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerContent
     */
    'content_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerContent
     */
    'message_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerContent
     */
    'template_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerContent
     */
    'enterprise_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerContent
     */
    'handlebars_text'?: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerContent
     */
    'vendor_template_id'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerContent
     */
    'x-konfig-original-example'?: Array<string>;
}

